name: Deploy Astro to GitHub Pages

on:
  schedule:
      - cron: '0 2 * * *'
  push:
    branches:
      - main  # Ensure this matches your default branch

permissions:
  contents: write  # Grants write access to repository contents

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: List repository files for debugging
      - name: List Repository Files
        run: |
          echo "Listing files in the repository root:"
          ls -al
          echo "Listing files recursively:"
          ls -alR

      # Step 3: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Updated to a supported version

      # Step 4: Cache node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 6: Build the Astro project
      - name: Build
        run: npm run build

      # Step 7: Create .nojekyll file
      - name: Create .nojekyll
        run: echo > dist/.nojekyll

      # Step 8: Create CNAME file
      - name: Create CNAME
        run: echo "www.bioai-rg.com" > dist/CNAME  # Replace with your actual domain

      # Step 9: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
