# .github/workflows/deploy.yml

name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main  # Ensure this matches your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: List repository files for debugging
      - name: List Repository Files
        run: |
          echo "Listing files in the repository root:"
          ls -al
          echo "Listing files recursively:"
          ls -alR

      # Step 3: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Updated to a supported version

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 5: Build the Astro project
      - name: Build
        run: npm run build

      # Step 6: Create .nojekyll file
      - name: Create .nojekyll
        run: echo > dist/.nojekyll

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
